apiVersion: v1
kind: Service
metadata:
  name: {{ include "zrok.fullname" . }}-frontend
  labels:
    {{- include "zrok.labelsFrontend" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.advertisedPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zrok.selectorLabelsFrontend" . | nindent 4 }}
