{{ if .Values.test.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: zrok-test-job
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: {{ .Values.test.backoffLimit }}
  template:
    spec:
      containers:
      - name: zrok
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["/bin/bash", "-c", "/zrok/test.bash"]
        env:
        - name: ZROK_API_ENDPOINT
          value: http://{{ include "zrok.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.controller.service.advertisedPort }}
        - name: HOME
          value: /tmp
        - name: PFXLOG_NO_JSON
          value: "true"
        - name: ZROK_ENABLE_TOKEN
          valueFrom:
            secretKeyRef:
              name: zrok-ziggy-account-token
              key: token
        volumeMounts:
        - name: test-script
          mountPath: /zrok/test.bash
          subPath: test.bash
          readOnly: true
      volumes:
      - name: test-script
        configMap:
          name: {{ include "zrok.fullname" . }}-config
          defaultMode: 0555
          items:
            - key: test.bash 
              path: test.bash

      restartPolicy: Never
{{- end }}