{{ if or (.Values.zitiIdentity) (.Values.zitiIdentityEncoding) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "httpbin.fullname" . }}-identity
type: Opaque
data:
  {{- if .Values.zitiIdentityEncoding }}
  ziti_identity_json: {{ .Values.zitiIdentityEncoding }}
  {{- else }}
  ziti_identity_json: {{ .Values.zitiIdentity | b64enc }}
  {{- end }}
{{- end }}

{{- if .Values.zitiEnrollment }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "httpbin.fullname" . }}-enrollment
data:
  ziti_enrollment_jwt: {{ .Values.zitiEnrollment | b64enc }}
{{- end }}
