---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "httpbin.fullname" . }}-hook-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "httpbin.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "httpbin.fullname" . }}-hook-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "httpbin.fullname" . }}-hook-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "httpbin.fullname" . }}-hook-role
subjects:
  - kind: ServiceAccount
    name: {{ include "httpbin.fullname" . }}-hook-serviceaccount
    namespace: {{ .Release.Namespace }}
