# Default values for ziti-console.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress:
  # -- create an ingress for the cluster service
  enabled: false
  # -- "nginx" if using ingress-nginx
  ingressClassName: ""
  # -- ingress annotations for the ingress controller
  annotations: {}
  # -- ingress labels
  labels: {}
  # -- DNS name the ingress should use for the console service
  advertisedHost:
  # -- enable TLS ingress by specifying the name of the secret with the tls.crt, tls.key, etc. for the server cert
  tlsSecret:

service:
  # -- create a cluster service for the deployment
  enabled: true
  # -- port for the server to bind and cluster service to target
  containerPort: 1408
  # -- port for the cluster service, load balancer, nodeport, and ingress to advertise
  advertisedPort: 80
  # -- symbolic name of the cluster service port
  portName: http
  # -- choose ClusterIP, NodePort, or LoadBalancer
  type: ClusterIP
  # -- cluster service labels
  labels: {}
  # -- cluster service annotations
  annotations: {}

settings:
  # -- Ziti Edge Mgmt APIs to pre-configure
  edgeControllers: []
    # - name: Ziti Edge Mgmt API
    #   # URL of controller's mgmt API cluster service
    #   url: https://myziti-controller-client.ziti-controller.svc:443
    #   # or https://myziti-controller-mgmt.ziti-controller.svc:443 if mgmt API is separate
    #   default: true
  # -- Ziti Fabric Mgmt APIs to pre-configure
  fabricControllers: []

image:
  # -- app container image to deploy 
  repository: openziti/zac
  # -- deployment image pull policy
  pullPolicy: Always
#  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: 0.26.11
#   command: ["sh", "-c", "while true; do sleep 11; done"]
  # -- app run command args
  args: []
  # -- app image registry credential
  pullSecrets: []
  # -- app run command
  command: ["node", "/usr/src/app/server.js"]
  # command: ["node", "/usr/src/app/server.js", "debug"]

# -- release name override
nameOverride: ""
# -- release fullname override
fullnameOverride: ""

# -- annotations to apply to all pods
podAnnotations: {}

podSecurityContext:
  # -- effective UID
  runAsUser: 1000
  # -- effective GID
  runAsGroup: 1000
  # -- volume mount filesystem group owner
  fsGroup: 1000

# -- deployment container security context
securityContext:
  # capabilities:
  #   add:
  #     - NET_ADMIN

# -- deployment container resources
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- deployment pod node selector
nodeSelector: {}
#  kubernetes.io/role: master

# -- deployment pod tolerations
tolerations: []
  # - key: node-role.kubernetes.io/master
  #   operator: Exists
  #   effect: NoSchedule

# -- deployment pod node affinity
affinity: {}

# -- deployment pod replicas
replicas: 1
