ctrlPlane:
  service:
    enabled: true
    type: ClusterIP
    annotations:
      kubernetes.io/ingress.class: nginx
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.allow-http: "false"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"

clientApi:
  service:
    enabled: true
    type: ClusterIP
    annotations:
      kubernetes.io/ingress.class: nginx
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.allow-http: "false"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
