clientApi:
  advertisedHost:
  advertisedPort: 443
  service:
    enabled: true
    type: ClusterIP
    annotations:
      kubernetes.io/ingress.class: nginx
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.allow-http: "false"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/secure-backends: "true"
