---
# Chart name: {{- .Chart.Name }} {{- .Values.nameOverride }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ziti-console.fullname" . }}-config
  labels:
    {{- include "ziti-console.labels" . | nindent 4 }}
data:
  settings-template.json: |-
    {{- toJson .Values.settings | nindent 4 }}

