apiVersion: v2
appVersion: 0.22.26
description: Host OpenZiti services with a tunneler pod
kubeVersion: '>= 1.20.0-0'
name: ziti-edge-tunnel
type: application
version: 0.0.14
icon: https://openziti.io/img/ziti-logo-dark.svg
home: https://openziti.io
sources:
- https://github.com/openziti/ziti-tunnel-sdk-c
keywords:
- openziti
- coredns
- node-local-dns
