apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ziti-host.fullname" . }}
  labels:
    {{- include "ziti-host.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "ziti-host.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ziti-host.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ziti-host.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- toYaml .Values.ports | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{ if .Values.image.command }}
          command: {{ .Values.image.command }}
          {{ end }}
          args:
            {{- toYaml .Values.image.args | nindent 12 }}
          env:
            - name: ZITI_IDENTITY_BASENAME
              value: {{ include "ziti-host.fullname" . }}-identity
          volumeMounts:
            - mountPath: /ziti-edge-tunnel
              name: persisted-identity
              readOnly: true
            {{- if .Values.spireAgent.enabled }}
            - mountPath: {{ .Values.spireAgent.spireSocketMnt }}
              name: spire-agent-socket
              readOnly: true
            {{- end }}
            {{- range .Values.additionalVolumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: persisted-identity
          secret:
          {{- if .Values.secret.existingSecretName }}
            secretName: {{ .Values.secret.existingSecretName }}
            defaultMode: 0444
            items:
            - key: {{ .Values.secret.keyName | default "persisted-identity" | quote }}
              path: {{ include "ziti-host.fullname" . }}-identity.json
          {{- else }}
            secretName: {{ include "ziti-host.fullname" . }}-identity
            defaultMode: 0444
            items:
            - key: persisted-identity
              path: {{ include "ziti-host.fullname" . }}-identity.json
          {{- end }}
        {{- if .Values.spireAgent.enabled }}
        - name: spire-agent-socket
          hostPath:
            path: {{ .Values.spireAgent.spireSocketMnt }}
            type: Directory
        {{- end }}
        {{- range .Values.additionalVolumes }}
        - name: {{ .name }}
          {{- if eq .volumeType "secret" }}
          secret:
            secretName: {{ .secretName }}
          {{- else if eq .volumeType "configMap" }}
          configMap:
            name: {{ .configMapName }}
          {{- else if eq .volumeType "emptyDir" }}
          emptyDir: {}
          {{- end }}
        {{- end }}

