#######
# CA to issue the controller's router control plane identity. This CA issues the
# server certificate that is presented by the controller to routers when they
# connect to the controller's "ctrl" endpoint, i.e. the router control plane. The
# same server certificate is re-used as a default identity if an alternative
# identity is not configured for a particular server TLS binding, e.g., web
# binding for the client API.
######
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ziti-controller.fullname" . }}-ctrl-plane-root-cert
  labels:
    {{- include "ziti-controller.labels" . | nindent 4 }}
spec:
  commonName: {{ include "ziti-controller.fullname" . }}-ctrl-plane-root
  secretName: {{ include "ziti-controller.fullname" . }}-ctrl-plane-root-secret
  isCA: true
  duration: {{ .Values.ca.duration }}
  renewBefore: {{ .Values.ca.renewBefore }}
  usages:
    - digital signature
    - cert sign
    - crl sign
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    kind: Issuer
    name: {{ include "ziti-controller.fullname" . }}-selfsigned-ca-issuer

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "ziti-controller.fullname" . }}-ctrl-plane-root-issuer
  labels:
    {{- include "ziti-controller.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "ziti-controller.fullname" . }}-ctrl-plane-root-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ziti-controller.fullname" . }}-ctrl-plane-intermediate-cert
  labels:
    {{- include "ziti-controller.labels" . | nindent 4 }}
spec:
  commonName: {{ include "ziti-controller.fullname" . }}-ctrl-plane-intermediate
  secretName: {{ include "ziti-controller.fullname" . }}-ctrl-plane-intermediate-secret
  isCA: true
  duration: {{ .Values.ca.duration }}
  renewBefore: {{ .Values.ca.renewBefore }}
  usages:
    - digital signature
    - cert sign
    - crl sign
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    {{- if .Values.ctrlPlane.alternativeIssuer }}
      {{- with .Values.ctrlPlane.alternativeIssuer }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- else }}
    kind: Issuer
    name: {{ include "ziti-controller.fullname" . }}-ctrl-plane-root-issuer
    {{- end }}

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "ziti-controller.fullname" . }}-ctrl-plane-intermediate-issuer
  labels:
    {{- include "ziti-controller.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "ziti-controller.fullname" . }}-ctrl-plane-intermediate-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ziti-controller.fullname" . }}-ctrl-plane-identity
  labels:
    {{- include "ziti-controller.labels" . | nindent 4 }}
spec:
  commonName: {{ include "ziti-controller.fullname" . }}-ctrl-plane-identity
  secretName: {{ include "ziti-controller.fullname" . }}-ctrl-plane-identity-secret
  isCA: false
  duration: {{ .Values.cert.duration }}
  renewBefore: {{ .Values.cert.renewBefore }}
  privateKey:
# It seems OSX has problems validating ECDSA tokens.. :-/
#    algorithm: ECDSA
#    size: 256
    algorithm: RSA
    size: 4096
  usages:
    - client auth # remove when we fix #ClientCertKeyReuseIssue
    - server auth
    - digital signature
    - content commitment
    - key encipherment
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - localhost
    - ziti-controller
    - {{ include "ziti-controller.fullname" . }}-ctrl
    - {{ include "ziti-controller.fullname" . }}-ctrl.{{ .Release.Namespace }}
    - {{ include "ziti-controller.fullname" . }}-ctrl.{{ .Release.Namespace }}.svc
    - {{ include "ziti-controller.fullname" . }}-ctrl.{{ .Release.Namespace }}.svc.cluster
    - {{ include "ziti-controller.fullname" . }}-ctrl.{{ .Release.Namespace }}.svc.cluster.local
    - {{ .Values.ctrlPlane.advertisedHost | default (printf "%s-ctrl.%s.svc.cluster.local" .Release.Name .Release.Namespace) }}
    {{- if .Values.ctrlPlane.dnsNames }}
      {{- range .Values.ctrlPlane.dnsNames }}
    - {{ . | quote }}
      {{- end }}
    {{- end }}
    {{- if and .Values.clientApi.service.enabled (not .Values.webBindingPki.enabled) }}
    - {{ include "ziti-controller.fullname" . }}-client
    - {{ include "ziti-controller.fullname" . }}-client.{{ .Release.Namespace }}
    - {{ include "ziti-controller.fullname" . }}-client.{{ .Release.Namespace }}.svc
    - {{ include "ziti-controller.fullname" . }}-client.{{ .Release.Namespace }}.svc.cluster
    - {{ include "ziti-controller.fullname" . }}-client.{{ .Release.Namespace }}.svc.cluster.local
    - {{ .Values.clientApi.advertisedHost }}
      {{- if .Values.clientApi.dnsNames }}
        {{- range .Values.clientApi.dnsNames }}
    - {{ . | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if and .Values.managementApi.service.enabled (not .Values.webBindingPki.enabled) }}
    - {{ include "ziti-controller.fullname" . }}-mgmt
    - {{ include "ziti-controller.fullname" . }}-mgmt.{{ .Release.Namespace }}
    - {{ include "ziti-controller.fullname" . }}-mgmt.{{ .Release.Namespace }}.svc
    - {{ include "ziti-controller.fullname" . }}-mgmt.{{ .Release.Namespace }}.svc.cluster
    - {{ include "ziti-controller.fullname" . }}-mgmt.{{ .Release.Namespace }}.svc.cluster.local
      {{- if .Values.managementApi.advertisedHost }}
    - {{ .Values.managementApi.advertisedHost }}
      {{- end }}
      {{- if .Values.managementApi.dnsNames }}
        {{- range .Values.managementApi.dnsNames }}
    - {{ . | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  # uris:
  #   - spiffe://cluster.local/ns/sandbox/sa/example
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    kind: Issuer
    name: {{ include "ziti-controller.fullname" . }}-ctrl-plane-intermediate-issuer
