{{- if .Values.defaultRouter.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-upgrade-job
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  completions: 1
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        {{- include "ziti-controller.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "ziti-controller.fullname" . }}-hook-serviceaccount
      containers:
      - name: post-upgrade-job
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: HOME
            value: {{ .Values.image.homeDir }}
          - name: ZITI_MGMT_API
            {{- if .Values.managementApi.service.enabled }}
            value: {{ include "ziti-controller.fullname" . }}-mgmt.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.managementApi.advertisedPort }}
            {{- else }}
            value: {{ include "ziti-controller.fullname" . }}-client.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.clientApi.advertisedPort }}
            {{- end }}
          # used by init script to branch on the condition where the identity
          # secret already exists
          - name: HELM_UPGRADE
            value: "true"
          - name: ZITI_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name:  {{ include "ziti-controller.fullname" . }}-admin-secret
                key: admin-user
          - name: ZITI_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  {{ include "ziti-controller.fullname" . }}-admin-secret
                key: admin-password
          - name: ZITI_CTRL_PLANE_CA
            value: {{ .Values.configMountDir }}/{{ .Values.ctrlPlaneCaDir }}
        volumeMounts:
          - mountPath: {{ .Values.execMountDir }}/create-default-router.bash
            name: ziti-controller-configmap
            subPath: create-default-router.bash
          - mountPath: {{ .Values.configMountDir }}/{{ .Values.ctrlPlaneCaDir }}
            name: ziti-controller-ctrl-plane-cas
            readOnly: true
          - mountPath: {{ .Values.execMountDir }}/zitiLogin
            name: ziti-controller-configmap
            subPath: zitiLogin
        command: ["create-default-router.bash"]
      volumes:
        - name: ziti-controller-configmap
          configMap:
            name: {{ include "ziti-controller.fullname" . }}-configmap
            items:
              - key: create-default-router.bash
                path: create-default-router.bash
                mode: 0555
              - key: zitiLogin
                path: zitiLogin
                mode: 0555
        - name: ziti-controller-ctrl-plane-cas
          configMap:
            name: {{ include "ziti-controller.fullname" . }}-ctrl-plane-cas
            defaultMode: 0444
{{- end }}
