
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ziti-controller.fullname" . }}-hook-serviceaccount
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ziti-controller.fullname" . }}-hook-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ziti-controller.fullname" . }}-hook-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ziti-controller.fullname" . }}-hook-role
subjects:
  - kind: ServiceAccount
    name: {{ include "ziti-controller.fullname" . }}-hook-serviceaccount
    namespace: {{ .Release.Namespace }}
