
{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace (printf "%s-%s" (include "ziti-router.fullname" . ) "hook-serviceaccount")) }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ziti-router.fullname" . }}-hook-serviceaccount
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ziti-router.fullname" . }}-hook-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ziti-router.fullname" . }}-hook-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ziti-router.fullname" . }}-hook-role
subjects:
  - kind: ServiceAccount
    name: {{ include "ziti-router.fullname" . }}-hook-serviceaccount
    namespace: {{ .Release.Namespace }}

{{- end }}
