{{- if and .Values.edge.enabled  .Values.edge.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ziti-router.fullname" . }}-edge
  labels:
  {{- include "ziti-router.labels" . | nindent 4 }}
  {{- with .Values.edge.service.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.edge.service.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- $type := default "ClusterIP" .Values.edge.service.type }}
  type: {{ $type }}
  {{- if eq $type "ClusterIP" }}
  {{- with .Values.edge.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- else if eq $type "LoadBalancer" }}
  {{- with .Values.edge.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.edge.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.edge.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.edge.service.sessionAffinity }}
  sessionAffinity: {{ .Values.edge.service.sessionAffinity }}
  {{- with .Values.edge.service.sessionAffinityConfig }}
  sessionAffinityConfig:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.edge.service.externalIPs }}
  externalIPs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.edge.service.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.edge.advertisedPort }}
      targetPort: {{ .Values.edge.containerPort }}
      protocol: TCP
      name: edge
      {{- if (eq $type "NodePort") }}
      nodePort: {{ .Values.edge.advertisedPort }}
      {{- end }}
  selector:
    {{- include "ziti-router.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "ziti-router"
{{- end }}

{{- if .Values.linkListeners.transport.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ziti-router.fullname" . }}-transport
  labels:
  {{- include "ziti-router.labels" . | nindent 4 }}
  {{- with .Values.linkListeners.transport.service.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.linkListeners.transport.service.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- $type := default "ClusterIP" .Values.linkListeners.transport.service.type }}
  type: {{ $type }}
  {{- if eq $type "ClusterIP" }}
  {{- with .Values.linkListeners.transport.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- else if eq $type "LoadBalancer" }}
  {{- with .Values.linkListeners.transport.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.linkListeners.transport.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.linkListeners.transport.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.linkListeners.transport.service.sessionAffinity }}
  sessionAffinity: {{ .Values.linkListeners.transport.service.sessionAffinity }}
  {{- with .Values.linkListeners.transport.service.sessionAffinityConfig }}
  sessionAffinityConfig:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.linkListeners.transport.service.externalIPs }}
  externalIPs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.linkListeners.transport.service.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.linkListeners.transport.advertisedPort }}
      targetPort: {{ .Values.linkListeners.transport.containerPort }}
      protocol: TCP
      name: transport
      {{- if (eq $type "NodePort") }}
      nodePort: {{ .Values.linkListeners.transport.port }}
      {{- end }}
  selector:
    {{- include "ziti-router.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "ziti-router"
{{- end }}

{{- if and .Values.tunnel.mode (eq .Values.tunnel.mode "proxy" ) .Values.tunnel.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ziti-router.fullname" . }}-proxy-default
  labels:
  {{- include "ziti-router.labels" . | nindent 4 }}
  {{- with .Values.tunnel.service.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tunnel.service.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- $type := default "ClusterIP" .Values.tunnel.service.type }}
  type: {{ $type }}
  {{- if eq $type "ClusterIP" }}
  {{- with .Values.tunnel.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- else if eq $type "LoadBalancer" }}
  {{- with .Values.tunnel.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.tunnel.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.tunnel.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.tunnel.service.sessionAffinity }}
  sessionAffinity: {{ .Values.tunnel.service.sessionAffinity }}
  {{- with .Values.tunnel.service.sessionAffinityConfig }}
  sessionAffinityConfig:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.tunnel.service.externalIPs }}
  externalIPs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tunnel.service.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
  {{- range .Values.tunnel.proxyServices }}
    {{- if or (not .k8sservice) (ne .k8sservice "default") }}
    - port: {{ .servicePort }}
      targetPort: {{ .listenPort }}
      protocol: {{ .serviceProtocol | default "TCP" }}
      name: {{ regexReplaceAll "\\W+" .zitiService "-" }}
      {{- if and (eq $type "NodePort") .serviceNodePort }}
      nodePort: {{ .serviceNodePort }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "ziti-router.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "ziti-router"
{{- end }}

{{- if and .Values.tunnel.mode (eq .Values.tunnel.mode "proxy" ) (gt (len .Values.tunnel.additionalK8sServices) 0) }}
{{- $root := . }}
{{- range .Values.tunnel.additionalK8sServices }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ziti-router.fullname" $root }}-proxy-{{ .name }}
  labels:
  {{- include "ziti-router.labels" $root | nindent 4 }}
  {{- with .labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- $type := default "ClusterIP" .type }}
  type: {{ $type }}
  {{- if eq $type "ClusterIP" }}
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- else if eq $type "LoadBalancer" }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if .sessionAffinity }}
  sessionAffinity: {{ .sessionAffinity }}
  {{- with .sessionAffinityConfig }}
  sessionAffinityConfig:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- with .externalIPs }}
  externalIPs:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
  {{- $service_name := .name }}
  {{- range $root.Values.tunnel.proxyServices }}
    {{- if and .k8sservice (eq .k8sservice $service_name) }}
    - port: {{ .servicePort }}
      targetPort: {{ .listenPortPort }}
      protocol: {{ .serviceProtocol | default "TCP" }}
      name: {{ regexReplaceAll "\\W+" .zitiService "-" }}
      {{- if and (eq $type "NodePort") .serviceNodePort }}
      nodePort: {{ .serviceNodePort }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "ziti-router.selectorLabels" $root | nindent 4 }}
    app.kubernetes.io/component: "ziti-router"
{{- end }}
{{- end }}
