name: Test charts in minikube
on:
  - pull_request
  - workflow_dispatch
jobs:
  miniziti:
    runs-on: ubuntu-latest
    name: deploy to minikube
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3

      - name: Start minikube
        uses: medyagh/setup-minikube@v0.0.14
        with:
          start-args: --profile miniziti

      - name: install ziti cli
        uses: supplypike/setup-bin@v3
        with:
          uri: https://github.com/openziti/ziti/releases/download/v0.29.0/ziti-linux-amd64-0.29.0.tar.gz
          name: ziti
          version: "0.29.0"

      - name: install miniziti script
        uses: supplypike/setup-bin@v3
        with:
          uri: https://raw.githubusercontent.com/openziti/ziti-doc/miniziti-no-hosts/docusaurus/docs/learn/quickstarts/network/miniziti.bash
          name: ziti
          version: "miniziti-no-hosts"

      - name: Run miniziti script with local charts
        run: |
          bash -x $(which miniziti.bash) -- --charts ./charts --verbose --no-hosts
