name: Release Helm Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - run: |
          while read -r DEP_REPO; do
            helm repo add "${DEP_REPO//(https:\/\/|\/)/_}" "${DEP_REPO}"
          done < <(
            for CHART_DIR in $(find ./charts -mindepth 2 -maxdepth 2 -type f -name Chart.yaml -exec dirname {} \;); do
              if [ -f "${CHART_DIR}/Chart.lock" ]; then
                awk '/repository:/ {print $2}' "./${CHART_DIR}/Chart.lock"
              fi
            done | sort -u
          )

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"

      - name: Push READMEs to gh-pages
        uses: netfoundry/git-push-action@main
        with:
          email: ${{ github.actor }}@github.com
          name: ${{ github.actor }}
          message: "auto-pushed to GH Pages from main"
          branch: gh-pages
